---
title: "Milestone 3 Paragraph"
author: "Daniel Shapiro"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This paper by Egor Lazarev entitled "Laws In Conflict: Legacies of War, Gender, and Legal Pluralism in Chechnya" examines post-war Chechnya and how legacies of war affect people's choice between various legal processes. In modern-day Chechnya, there are three competing legal bodies: official Russian law, sharia courts, and customary law (adat). The author argues that sharia and adat courts are traditionally more discriminatory towards women, and that women are more likely than men to turn to state courts rather than sharia courts or adat. The pattern of women choosing to turn to state courts for legal disputes rather than sharia or customary courts is exacerbated, as the author works to show through data, by the level to which a region was affected by violence during the Chechen wars. In other words, conflict provided women with more opportunity to pursue their interests through official law. The author, Egor Lazarev, backs up his claim through data and through a comparison with neighboring Ingushetia, which has many similarities but has not gone through conflict. The enhanced opportunities for women in the legal process has been counterbalanced by an effort by the Ramzan Kadyrov government in Chechnya to retraditionalize the republic, and while women continue to look to state courts for assistance, Kadyrov works toward supporting more traditional forms of conflict resolution that favor men and Chechnya's traditionally patriarchal society. The author concludes that gender can play a large role in forming splits in postconflict societies.

My github repo is: https://github.com/dfshapir/Replication. Here, you can open up my Milestone-3.Rmd and my Milestone-3.html to view my extensive code comments. 